=== sercan447/xml-xsd-dersleri/src/main/java/com/burakkutbay/xml/xsd/marka.xsd
<?xml version="1.0" ?>
    <schema xmlns="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.restoranduragi.com/ogrenciler"
    xmlns:tns="http://www.example.org/ogrenciler"
               elementFromDefault="unqualified">
    
        <complexType name="adrestipi">
            <sequence>
                <element name="sehir" type="string" ></element>
                <element name="cadde" type="string"></element>
                <element name="mahalle" type="string"></element>
            </sequence>
        </complexType>
        
        <complexType name="derstipi">
            <sequence>
                <element name="kod" type="integer"></element>
                <element name="ad" type="string"></element>     
            </sequence>
        </complexType>
    
        <complexType name="derslertipi">
            <sequence>
                <element name="ders" type="tns:derstipi" minOccurs="1" maxOccurs="unbounded" ></element>
            </sequence>
        </complexType>
        
        
        <complexType name="ogrencitipi">
            <sequence>
                <element name="isim" type="string" minOccurs="1" maxOccurs="1" ></element>
                <element name="soyad" type="string" minOccurs="1" maxOccurs="1"></element>
                <element name="adres" type="tns:adrestipi"></element>
                <element name="dersler" type="tns:derslertipi"></element>
            </sequence>
            <attribute name="no" type="int" ></attribute>
        </complexType>
    
    
        <complexType name="ogrencilerTipi">
            <sequence>
                <element name="ogrenci" type="tns:ogrencitipi" minOccurs="1" ></element>
            </sequence>
        </complexType>
    
        <element name="ogrenciler" type="tns:ogrencilerTipi"></element>
            
    
    
    </schema>

=== sercan447/xml-xsd-dersleri/src/main/java/com/burakkutbay/xml/xsd/markalan.xml
<?xml version="1.0" encoding="UTF-8"?>

<tns:ogrenciler
xmlns:tns="http://www.restoranduragi.com/ogrenciler"
xmlns:xsi="http://www.w3.org/XMLSchema-instance"
xsi:schemaLocation="http://www.example.org/ogrenciler marka.xsd">
    <ogrenci no="5">
            <ad>SERCAN</ad>
            <soyad>YERGOK</soyad>

            <adres>
                <sehir>AYDIN</sehir>
                <cadde>NAZILLI</cadde>
                <mahalle>TURGUT REIS</mahalle>
            </adres>

            <dersler>
                <ders>
                    <kod>48934</kod>
                    <ad>JAVA EE</ad>
                </ders>
            </dersler>
    </ogrenci>
</tns:ogrenciler>
